import { useEffect } from "react";
import { Link, useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import { ArrowLeft, Share2, Calendar, Sparkles, AlertTriangle, Lightbulb, ChevronRight, FileText, ShieldCheck, Activity, Stethoscope } from "lucide-react";
import { useAssessment } from "@/context/AssessmentContext";
import { getOverallRisk, getPrimaryResult, getRecommendation, getRiskBreakdown, getSignalCount } from "@/lib/report";
import { RiskGauge } from "@/components/dashboard/RiskGauge";
import { FactorBarChart } from "@/components/dashboard/BarChart";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Badge, StatusPill } from "@/components/ui/Badge";
import { FadeIn, Stagger, StaggerItem } from "@/components/ui/PageContainer";
import { cn } from "@/lib/utils";
import { AnimatedNumber } from "@/components/ui/AnimatedNumber";

const riskVariant = (risk: string) => risk === "High" ? "danger" : risk === "Moderate" ? "warning" : "success";

export function DashboardPage() {
  const navigate = useNavigate();
  const { patient, report } = useAssessment();

  useEffect(() => { if (!report) navigate("/assessment", { replace: true }); }, [navigate, report]);
  if (!report) return null;

  const overall = getOverallRisk(report);
  const breakdown = getRiskBreakdown(report);
  const primary = getPrimaryResult(report);
  const recommendation = getRecommendation(report);
  const signalCount = getSignalCount(report);
  const displayName = patient.personal_information.full_name || "Patient";
  const nextSteps = recommendation?.next_steps ?? [];

  return <div className="min-h-screen bg-gradient-soft">
    <div className="border-b border-surface-border bg-white/80 backdrop-blur-xl sticky top-0 z-30"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3 px-5 py-4 sm:flex-nowrap sm:px-8 sm:gap-4"><button onClick={() => navigate("/")} className="inline-flex items-center gap-2 text-sm text-navy-300 hover:text-navy transition-colors"><ArrowLeft size={16} /><span>Back</span></button><StatusPill status="complete" className="order-3 sm:order-none">Report generated</StatusPill><div className="flex flex-wrap items-center justify-end gap-2"><Button variant="outline" size="sm"><Share2 size={14} />Share with Doctor</Button><Button variant="primary" size="sm" className="header-report-button" asChild><Link to="/report"><FileText size={14} />View Full Report</Link></Button></div></div></div>

    <div className="mx-auto max-w-7xl px-5 sm:px-8 py-8 sm:py-12">
      <FadeIn><div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4"><div><p className="text-sm text-navy-200">Assessment completed · just now</p><h1 className="mt-1 text-display-md text-navy text-balance">Hello, {displayName}. Here's your <span className="gradient-text">risk assessment</span>.</h1></div><div className="flex items-center gap-2 text-xs text-navy-300"><ShieldCheck size={14} className="text-success-500" /><span>Your assessment data is protected</span></div></div></FadeIn>

      <div className="mt-8 grid lg:grid-cols-12 gap-5">
        <FadeIn delay={0.05} className="lg:col-span-5"><Card className="p-6 sm:p-8 h-full relative overflow-hidden"><div className="absolute -top-20 -right-16 h-52 w-52 rounded-full bg-success-500/10 blur-3xl" /><div className="relative"><Badge variant="success" className="px-2.5 py-1"><Sparkles size={11} />CuraCore™ estimate</Badge><h3 className="mt-3 text-2xl font-semibold tracking-tight text-navy">{overall.level} risk profile detected</h3><p className="mt-2 max-w-xl text-sm leading-relaxed text-navy-300">Based on <AnimatedNumber value={signalCount} /> matched risk signals across your assessment. Review the cancer-specific breakdown and recommended next steps below.</p><div className="mt-6 border-t border-surface-border/80 pt-6"><div className="mx-auto w-full max-w-[190px]"><RiskGauge value={overall.score} size={190} /></div><div className="mt-6 grid grid-cols-3 divide-x divide-surface-border"><Metric className="px-2 text-center" label="Overall score" value={overall.score} /><Metric className="px-2 text-center" label="Signals" value={signalCount} /><Metric className="px-2 text-center" label="Cancer types" value={breakdown.length} /></div></div></div></Card></FadeIn>
        <FadeIn delay={0.1} className="lg:col-span-4"><Card className="p-6 h-full"><div className="flex items-center justify-between"><div><h3 className="text-lg font-semibold text-navy">Risk factor breakdown</h3><p className="text-xs text-navy-200 mt-0.5">Cancer-specific scores from CuraCore™</p></div><Badge variant="ai" className="px-2 py-0.5 text-[10px]"><Sparkles size={10} />Explainable</Badge></div><div className="mt-6"><FactorBarChart data={breakdown} /></div></Card></FadeIn>
        <FadeIn delay={0.15} className="lg:col-span-3 flex flex-col gap-5"><Card className="p-6 relative overflow-hidden"><div className="absolute -top-10 -right-10 h-32 w-32 rounded-full bg-medical-500/10 blur-2xl" /><p className="text-xs font-semibold uppercase tracking-wider text-navy-200">Highest-priority area</p><p className="health-value mt-2 text-3xl font-bold tracking-tight text-navy capitalize">{primary ? breakdown.find((item) => item.score === primary.score)?.label : "—"}</p><p className="mt-1.5 text-xs text-navy-300">{primary?.recommendation.urgency ?? "No recommendation available"}</p></Card><Card className="p-6"><p className="text-xs font-semibold uppercase tracking-wider text-navy-200">Recommended specialist</p><p className="health-value mt-2 text-xl font-bold text-navy">{recommendation?.specialist ?? "General Physician"}</p><p className="mt-1 text-xs text-navy-300">Based on the highest current risk score</p><Button variant="outline" size="sm" className="mt-4 w-full"><Calendar size={14} />Schedule reminder</Button></Card><Link to="/report" className="block"><Card className="final-report-card group relative overflow-hidden p-5 transition-all duration-300 hover:-translate-y-0.5"><div className="absolute -right-5 -top-5 h-20 w-20 rounded-full bg-success-500/20 blur-2xl transition-opacity group-hover:opacity-100" /><div className="relative flex items-center gap-3"><div className="final-report-icon flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-success-50 text-success-600"><FileText size={18} /></div><div className="min-w-0 flex-1"><p className="text-xs font-semibold uppercase tracking-wider text-navy-200">Ready to view</p><p className="mt-0.5 text-base font-semibold text-accent-500">Final Report</p></div><ChevronRight size={18} className="text-accent-500 transition-transform group-hover:translate-x-1" /></div></Card></Link></FadeIn>
      </div>

      <FadeIn delay={0.18} className="mt-5"><Card className="assessment-recommendation relative overflow-hidden px-6 py-5 sm:px-8"><div className="absolute -right-10 top-1/2 h-28 w-28 -translate-y-1/2 rounded-full bg-success-500/10 blur-3xl" /><div className="relative flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0 flex items-start gap-3"><div className="recommendation-summary-icon flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-success-50 text-success-600"><ShieldCheck size={19} /></div><div><p className="text-xs font-semibold uppercase tracking-wider text-navy-200">Assessment recommendation</p><p className="mt-1 text-sm font-semibold text-navy sm:text-base">{recommendation?.action ?? "Review your assessment results with a healthcare professional."}</p></div></div><Badge variant={riskVariant(overall.level)} className="shrink-0 self-start whitespace-nowrap px-3 sm:self-center">{overall.level} risk plan</Badge></div></Card></FadeIn>

      <div className="mt-5 grid lg:grid-cols-12 gap-5"><FadeIn delay={0.25} className="lg:col-span-7"><Card className="p-6 sm:p-8 h-full"><div className="flex items-center justify-between"><div><h3 className="text-lg font-semibold text-navy">CuraCore™ recommended next steps</h3><p className="text-sm text-navy-300 mt-0.5">Generated from your highest-priority risk profile</p></div><Badge variant="ai"><Sparkles size={11} />Personalized</Badge></div><div className="mt-6 space-y-3">{nextSteps.map((step) => <RecommendationItem key={step} title={step} priority={recommendation?.urgency ?? overall.level} priorityVariant={riskVariant(overall.level)} />)}</div><div className="mt-7 flex flex-wrap gap-3"><Button variant="primary" size="md" asChild><Link to="/report"><FileText size={14} />View CuraCore™ Report</Link></Button><Button variant="outline" size="md"><Calendar size={14} />Book Appointment</Button></div></Card></FadeIn>
      <FadeIn delay={0.3} className="lg:col-span-5"><Card className="p-6 sm:p-8 h-full"><div className="flex items-center justify-between"><div><h3 className="text-lg font-semibold text-navy">Assessment results</h3><p className="text-sm text-navy-300 mt-0.5">Cancer-specific risk levels</p></div><Badge variant={riskVariant(overall.level)}>{overall.level}</Badge></div><div className="mt-6 space-y-3">{breakdown.map((item) => <div key={item.label} className="flex items-center justify-between rounded-xl border border-surface-border px-4 py-3"><div><p className="text-sm font-semibold text-navy">{item.label}</p><p className="text-xs text-navy-200">Score <AnimatedNumber value={item.score} /></p></div><Badge variant={riskVariant(item.risk)}>{item.risk}</Badge></div>)}</div></Card></FadeIn></div>

      <FadeIn delay={0.35} className="mt-5"><Card className="p-6 sm:p-8"><div className="flex items-start gap-3"><div className="h-10 w-10 rounded-xl bg-gradient-to-br from-medical-500 to-cyan-400 flex items-center justify-center text-white"><Lightbulb size={18} /></div><div><h3 className="text-lg font-semibold text-navy">Why did CuraCore™ reach this conclusion?</h3><p className="text-sm text-navy-300 mt-0.5 max-w-2xl">Matched factors from the backend risk-engine rules.</p></div></div><Stagger className="explanation-grid mt-7 grid md:grid-cols-2 gap-4" delay={0.08}>{breakdown.flatMap((item) => report.report[item.key]?.reasons.map((reason) => ({ item, reason })) ?? []).map(({ item, reason }) => <ReasonCard key={`${item.key}-${reason}`} title={item.label} body={reason} impact={`Score ${item.score}`} color={item.risk === "High" ? "amber" : item.risk === "Moderate" ? "info" : "success"} icon={item.risk === "High" ? Stethoscope : Activity} />)}</Stagger></Card></FadeIn>
      <FadeIn delay={0.4} className="mt-5"><div className="ai-disclaimer rounded-2xl border border-amber-200 bg-amber-50/50 p-5 sm:p-6 flex items-start gap-3"><div className="h-9 w-9 rounded-lg bg-amber-100 flex items-center justify-center shrink-0"><AlertTriangle size={16} className="text-amber-700" /></div><div><p className="text-sm font-semibold text-amber-900">This is a CuraCore™ risk estimate, not a diagnosis.</p><p className="mt-1 text-xs text-amber-800/80 leading-relaxed max-w-3xl">CuraMind provides clinical decision support to help you and your healthcare provider make informed screening decisions. Please discuss your results with a qualified medical professional.</p></div></div></FadeIn>
    </div>
  </div>;
}

function Metric({ label, value, className }: { label: string; value: number; className?: string }) { return <div className={cn("min-w-0", className)}><p className="text-[10px] font-semibold uppercase tracking-wider text-navy-200">{label}</p><p className="health-value text-base font-semibold text-navy mt-0.5"><AnimatedNumber value={value} /></p></div>; }
function RecommendationItem({ title, priority, priorityVariant }: { title: string; priority: string; priorityVariant: "danger" | "warning" | "success" }) { return <div className="flex flex-col gap-3 rounded-xl border border-surface-border p-4 transition-all hover:border-navy-200/60 hover:bg-surface-subtle/50 sm:grid sm:grid-cols-[2.25rem_minmax(0,1fr)_13rem] sm:items-center sm:gap-4"><div className="recommendation-icon flex h-9 w-9 items-center justify-center rounded-lg border border-medical-100 bg-gradient-to-br from-medical-50 to-cyan-50"><ChevronRight size={16} className="text-medical-500" /></div><p className="min-w-0 text-sm font-semibold leading-relaxed text-navy">{title}</p><div className="w-full sm:w-52 sm:justify-self-end"><Badge variant={priorityVariant} className="w-full justify-center whitespace-normal px-3 py-1.5 text-center text-[10px] leading-4">{priority}</Badge></div></div>; }
function ReasonCard({ title, body, impact, color, icon: Icon }: { title: string; body: string; impact: string; color: "amber" | "success" | "info"; icon: typeof Activity }) { const map = { amber: "bg-amber-50 text-amber-700 border-amber-200", success: "bg-success-50 text-success-600 border-success-100", info: "bg-medical-50 text-medical-600 border-medical-100" }; return <StaggerItem><div className="relative rounded-2xl border p-5 bg-white hover:shadow-soft transition-all group"><div className="flex items-start justify-between gap-3"><div className="flex items-start gap-3"><div className={cn("h-9 w-9 rounded-lg flex items-center justify-center border", map[color])}><Icon size={16} /></div><div><p className="text-sm font-semibold text-navy">{title}</p><p className="text-xs text-navy-300 mt-1 leading-relaxed">{body}</p></div></div><span className={cn("text-xs font-semibold tabular-nums px-2 py-0.5 rounded-full border", map[color])}>{impact}</span></div></div></StaggerItem>; }
